### ISSUE TITLE
syntax for "include" (or exclude) to reduce payload size to only a few selected attributes/fields (type, id, name)

### ISSUE THREAD

**Issue by pvcon13** [GovTribe/api#1]
This is a question not an issue. Thank you

**Comment by jhariani** [comment]
Sure, the API implements JSON API, so you can follow the guidance on sparse field sets [here](https://jsonapi.org/format/#fetching-sparse-fieldsets). For example, if you only wanted to load the acronyms field for a Federal Agency, you could specify that like so:

```
https://govtribe.com/api/1.0.0/federal-agency/7200|7200|VPUSAIDOM-A?fields[federal-agency]=acronyms
```

**Comment by pvcon13** [comment]
Thank you.
